import type { Metadata } from "next";
import { Geist, Geist_Mono, Google_Sans_Code, WDXL_Lubrifont_JP_N, Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";
import Side from "./_components/Side";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import CustomThemeProvider from "./_components/CustomThemeProvider";
import AppTitle from "./_components/AppTitle";
import CommonSection from "./_components/CommonSection";
import styles from "./layout.module.css";
import CommonFooter from "./_components/CommonFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <CustomThemeProvider>
            <AppTitle />
            <CommonSection>
              <div className={styles.rootDiv}>
                <Side />
                {children}
              </div>
            </CommonSection>
            <CommonFooter />
          </CustomThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
